#cloud-config
coreos:
  fleet:
    etcd_servers: "http://192.168.2.3:4001"
  units:
    - name: format-sda.service
      command: start
      content: |
        [Unit]
        Description=Formats sda
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        ExecStart=/usr/sbin/wipefs -f /dev/sda
        ExecStart=/usr/sbin/mkfs.btrfs -f /dev/sda
    - name: var-lib-docker.mount
      command: start
      content: |
        [Unit]
        Description=Mount sda to /var/lib/docker
        Requires=format-sda.service
        After=format-sda.service
        Before=docker.service
        [Mount]
        What=/dev/sda
        Where=/var/lib/docker
        Type=btrfs
    - name: fleet.service
      command: start
    - name: docker.service
      command: start
ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key
