- name: Install nginx
  apt: name=nginx

- name: put nginx conf
  copy: src=etc/nginx/nginx.conf dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: put default site.
  copy: src=etc/nginx/sites-enabled/default dest=/etc/nginx/sites-enabled/default
  notify:
    - restart nginx

- name: Put etcd cloud config.
  copy: src=pxe/nginx/pxe-cloud-config.yml.etcd1 dest=/pxe/nginx/cloud-config.yml.etcd1

- name: Put normal cloud config.
  copy: src=pxe/nginx/pxe-cloud-config.yml dest=/pxe/nginx/cloud-config.yml
