- name: Update the apt cache
  apt: update_cache=yes

- name: Install syslinux, for pxelinux.0
  apt: name=syslinux-common

- name: Install dnsmasq
  apt: name=dnsmasq

- name: Put dnsmasq config
  copy: src=etc/dnsmasq.conf dest=/etc/dnsmasq.conf

- name: Put /pxe/pxelinux.cfg/default
  copy: src=pxe/ dest=/pxe

- name: Put pxelinux.0 in pxe folder
  command: cp /usr/lib/syslinux/pxelinux.0 /pxe

- name: Get http://alpha.release.core-os.net/amd64-usr/current/coreos_production_pxe.vmlinuz
  get_url: url=http://alpha.release.core-os.net/amd64-usr/current/coreos_production_pxe.vmlinuz dest=/pxe/coreos_production_pxe.vmlinuz

- name: Get http://alpha.release.core-os.net/amd64-usr/current/coreos_production_pxe_image.cpio.gz
  get_url: url=http://alpha.release.core-os.net/amd64-usr/current/coreos_production_pxe_image.cpio.gz dest=/pxe/coreos_production_pxe_image.cpio.gz