- name: Update the apt cache
  apt: update_cache=yes

- name: Install syslinux, for pxelinux.0
  apt: name=syslinux-common

- name: Install dnsmasq
  apt: name=dnsmasq

- name: Put dnsmasq config
  copy: src=etc/dnsmasq.conf dest=/etc/dnsmasq.conf

- name: Creates folder for pxe files
  file: path=/pxe state=directory

- name: Put pxelinux.0 in pxe folder
  command: cp /usr/lib/syslinux/pxelinux.0 /pxe

- name: Creates pxelinux.cfg folder
  file: path=/pxe/pxelinux.cfg state=directory

- name: Put coreos pxelinux.cfg
  copy: src=pxe/pxelinux.cfg/default dest=/pxe/pxelinux.cfg/default

- name: Get http://alpha.release.core-os.net/amd64-usr/current/coreos_production_pxe.vmlinuz
  get_url: url=http://alpha.release.core-os.net/amd64-usr/current/coreos_production_pxe.vmlinuz dest=/pxe

- name: Get http://alpha.release.core-os.net/amd64-usr/current/coreos_production_pxe_image.cpio.zg
  get_url: url=http://alpha.release.core-os.net/amd64-usr/current/coreos_production_pxe_image.cpio.zg dest=/pxe